#!/bin/bash
# Test Script for NADRA Performance Optimizations
# This script validates the new Bull job queue and index analyzer

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  NADRA Performance Optimization - Testing Guide            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "📋 TESTS TO RUN:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Test 1: Check dependencies
echo "✅ TEST 1: Check New Dependencies"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Command: npm ls bullmq redis"
echo ""
echo "Expected Output:"
echo "  nadra-system@0.1.0 /path/to/nadra-system"
echo "  ├── bullmq@5.11.4"
echo "  └── redis@4.7.0"
echo ""

# Test 2: Check job queue file exists
echo "✅ TEST 2: Verify Job Queue Module"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "File: lib/jobQueue.js"
echo "Check: Exports queueEmail, getQueueStats, closeQueue"
echo ""
echo "Command to verify:"
echo "  grep -E 'export.*queueEmail|export.*getQueueStats' lib/jobQueue.js"
echo ""

# Test 3: Check updated routes
echo "✅ TEST 3: Verify Email Routes Updated"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Files to check:"
echo "  1. lib/ticketHelper.js - Should import queueEmail"
echo "  2. app/api/payments/process/route.js - Should use queueEmail"
echo "  3. app/api/tickets/update/[ticketId]/route.js - Should use queueEmail"
echo "  4. app/api/delivery/[id]/update/route.js - Should use queueEmail"
echo ""
echo "Grep command:"
echo "  grep -r 'queueEmail' lib/ app/api/"
echo ""

# Test 4: Check index analyzer
echo "✅ TEST 4: Verify Index Analyzer Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "File: scripts/analyzeIndexes.js"
echo "Command:"
echo "  node scripts/analyzeIndexes.js"
echo ""
echo "Expected Output:"
echo "  - Connection confirmation"
echo "  - Table and index analysis"
echo "  - Recommendations (if any)"
echo "  - JSON file saved with timestamp"
echo ""

# Test 5: API functionality
echo "✅ TEST 5: Verify API Functionality (Manually)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After starting 'npm run dev', test these endpoints:"
echo ""
echo "1. Create a ticket (should return quickly):"
echo "   POST /api/tickets/create"
echo "   Body: {"
echo "     \"serviceId\": 1,"
echo "     \"customerPriority\": \"NORMAL\","
echo "     \"userId\": 1"
echo "   }"
echo ""
echo "2. Expected: Response < 50ms (no email blocking)"
echo ""
echo "3. Process payment:"
echo "   POST /api/payments/process"
echo "   Body: {"
echo "     \"ticketId\": 1,"
echo "     \"paymentMethod\": \"ONLINE\","
echo "     \"cardDetails\": {"
echo "       \"cardNumber\": \"1234567890123456\","
echo "       \"cvv\": \"123\","
echo "       \"expiryDate\": \"1225\""
echo "     }"
echo "   }"
echo ""
echo "4. Update delivery:"
echo "   PATCH /api/delivery/1/update"
echo "   Body: {"
echo "     \"status\": \"DISPATCHED\","
echo "     \"trackingNumber\": \"TRK123456\""
echo "   }"
echo ""

# Test 6: Redis connection
echo "✅ TEST 6: Verify Redis Connection (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "If Redis is running:"
echo ""
echo "  redis-cli ping"
echo "  # Output: PONG"
echo ""
echo "To monitor queue:"
echo "  redis-cli MONITOR"
echo ""
echo "To check queue contents:"
echo "  redis-cli"
echo "  > KEYS nadra*"
echo "  > HGETALL nadra-emails"
echo ""

# Test 7: Email verification
echo "✅ TEST 7: Verify Emails Arrive"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Create/update ticket that triggers email"
echo "2. Check email inbox (may take 5-10 seconds)"
echo "3. Emails should arrive with correct content"
echo "4. If no email:"
echo "   - Check .env.local has EMAIL_USER and EMAIL_PASS"
echo "   - Check Redis connection (if configured)"
echo "   - Check logs for errors"
echo ""

# Test 8: Performance comparison
echo "✅ TEST 8: Performance Comparison"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Before: API waits for email (slow)"
echo "After: API returns immediately, email queued (fast)"
echo ""
echo "Measure API response time:"
echo ""
echo "  time curl -X POST http://localhost:3000/api/tickets/create \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"serviceId\": 1, \"customerPriority\": \"NORMAL\", \"userId\": 1}'"
echo ""
echo "Expected: < 50ms"
echo ""

# Test 9: Fallback testing
echo "✅ TEST 9: Test Fallback (Without Redis)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Start server without Redis running"
echo "2. Create ticket that should send email"
echo "3. Email should still arrive (synchronous sending)"
echo "4. No errors in console"
echo ""

# Test 10: Queue stats
echo "✅ TEST 10: Check Queue Statistics"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "In Node.js repl or API:"
echo ""
echo "  import { getQueueStats } from '@/lib/jobQueue';"
echo "  const stats = await getQueueStats();"
echo "  console.log(stats);"
echo ""
echo "Expected output:"
echo "  {"
echo "    available: true,"
echo "    jobs: {"
echo "      waiting: 0,"
echo "      active: 0,"
echo "      completed: 10,"
echo "      failed: 0"
echo "    },"
echo "    timestamp: '2025-12-05T...'"
echo "  }"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🎯 QUICK TEST CHECKLIST                                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "☐ npm install runs without errors"
echo "☐ npm run dev starts successfully"
echo "☐ Dependencies check: npm ls bullmq redis"
echo "☐ Files exist:"
echo "  ☐ lib/jobQueue.js"
echo "  ☐ scripts/analyzeIndexes.js"
echo "  ☐ PERFORMANCE_GUIDE.md"
echo "  ☐ IMPLEMENTATION_SUMMARY.md"
echo "☐ grep -r 'queueEmail' finds 4+ matches"
echo "☐ Create ticket API returns < 50ms"
echo "☐ Email arrives within 10 seconds"
echo "☐ No errors in console"
echo "☐ Index analyzer runs: node scripts/analyzeIndexes.js"
echo "☐ Dashboard still works normally"
echo "☐ Existing tests pass"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}✅ All tests passed = System is working correctly!${NC}"
echo ""
echo "For detailed info, see PERFORMANCE_GUIDE.md"
echo ""
