-- Update OTP table for SMS support
ALTER TABLE `OTP` MODIFY COLUMN `email` VARCHAR(191) NULL;
ALTER TABLE `OTP` MODIFY COLUMN `code` VARCHAR(191) NULL;
ALTER TABLE `OTP` ADD COLUMN `phoneNumber` VARCHAR(191) NULL;
ALTER TABLE `OTP` ADD COLUMN `otp` VARCHAR(191) NULL;
ALTER TABLE `OTP` ADD COLUMN `expiresAt` DATETIME(3) NULL;
ALTER TABLE `OTP` ADD COLUMN `verified` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `OTP` ADD COLUMN `metadata` TEXT NULL;
